apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  GITHUB_WEBHOOK_SECRET: "codeSentry_12140927"
  GITHUB_APP_ID: "4863708"
  GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAs2zOI6yiR2ERyaJAqymml5RALf3WkrDiypA+CG4Nt7SDiD8+
    dBsoPoZTLFTo5zE6Hz+TIYzQnF8CsgQZMPij5tYFLgMXoFguJxjAkLY7wh0pGotb
    oVGSnYEkpgJhvGL2nIfRqp4uKzhDQ20CZHddDodo5Bge4EUm27NUF0mFrwyMUsgj
    9fAPN2G8AnmV3cAHFPVGWhsa01Jp6KHBmBSIiwVfERIOScXdd364sNvSnDRyASY0
    O9uv4gxvqqACiNfy6fRiJu4TJf0rGqa212Q0ArIo9tegcjBOq99V41mLhk8FyNnC
    3HVmS4bp1sdS9YUFSNIggqUDgzdaiqcv6Q2UhwIDAQABAoIBAA+Y2L6PJjgwPvyZ
    Jyf54epxT7bvxvRPfhd/vHS9JGIgxgJVBRfQuIne4WIMK4bVZ6kJvL+A3y2IsNJK
    uunf41eQqTibujUNFU3+v9aUkNNJ96XAEYIPdkBM1qO7t0VKEQgAYoCDaZ4GMQqu
    cjPLkIJP0RVq51w1hrA4gYnYsU9LEX7uUrxF9rSUHspoWEjOSCKSeFmvvu/VLcqF
    AF/uDJMT4YDQrfuPEq3g7mT8A7DGBhkDjoJVWcyuy/zpc7qEWrafBUEu3K6XAtO2
    V3i5ScLFERNNOhqooAkiiHFZGzVgiU/K/lghHlfBoH8hYTxinH704KioTrERRKFZ
    WLlbcrkCgYEA7WFiq0p6FHLVbbkyYzwQ5jz1vupix0FLztP9hpEt7AGkzUed/6vz
    IDofKXXpXaJV95mhKz6vE/HanvsIfK+p18rjqse0UvRay9Ck46J5aAkv48mrZ+8H
    ePZON/1hq/KD6N8LIHSDSy1Tgp2sTM+UDbp4iB8tzfZPEUPM8UfAsdMCgYEAwX+r
    8iZUR1BxA1q1CPgdid2WhGstW0X9L6cB1j0elDfAy9AYfJvjcdbkVTjFlJ7XeVL/
    3c97D7ET5xO7+2bzAT1GMhU1+3Guh/fyUFmvgSdZ7Lnagk1iJFAe9Bz9dx/ew5Dd
    gITRmJWv0cbtzVCXo8UcL2TntottIWQP2ZUdbf0CgYEAtvGy5WhEpbXKnwF3v9ru
    +0JH8pcZAY9lKUVfwnHo/lZV+I8VSZHvkgq5MW7aJ3uQ3X3dJELvE2P1pUi6xb1s
    HA8VXu0CIFyKDUIDkhwJjRBnhBpMq5EgJS1OIwB4YdhJqRMctCqXdTy9e5Cg1aG0
    7M+lTOManf0R+rBSJjGyZFkCgYAIcndiKdQyDMvyNoqCqro3Y4oHm9ouCt8jrmnB
    HYfxNoHfI+V9wxxpwtTS95iAhXKopDvxRfZ8V+Gji9QABJ2FJ1SiKRTjNjJFU0ir
    w06LF9mwIOjuGUy4gxrm00EpayXBadiRnLq9q4MyaDnHZcZI6vjxBLms2WdZNtIO
    UJkpTQKBgQDfQCku9E7nZpdhUe6Gjrc9F6yI7AFfak9h/9JY4oU8oh33fUrO1gNV
    cyBoDO/hmjOaV7QSOULNBNkMgTq+ayHFca+qQRK4ilE6nwqP413eubUXypjra3oX
    w5R/U0BTlLHpKneafIrPmC94i2qhX4DmliGThcpYfe/rqAL3WdVTJg==
    -----END RSA PRIVATE KEY-----
  OPENAI_API_KEY: ""
  LANGFUSE_PUBLIC_KEY: "pk-lf-fb0a6774-a0b8-40af-8a1f-7177e9664ce6"
  LANGFUSE_SECRET_KEY: "sk-lf-00e9eee9-5768-4264-9971-c7450d8290e3"
  DATABASE_URL: "postgresql+asyncpg://dbadmin:codesentry12140927@code-sentry-pull-analyze-postgres.ckbmksc4if3t.us-east-1.rds.amazonaws.com"
